name = "crowdpunkdao-mailer"
main = "dist/index.mjs"
compatibility_date = "2022-05-28"
compatibility_flags = []
account_id = "82321a9ff91bb528e4b1d1541178417f"

[build]
command = "node build.js"

[env.staging]
workers_dev = true
name = "crowdpunkdao-mailer-staging"
kv_namespaces = [ 
         { binding = "CROWDPUNK_NAMESPACE", id = "fff8e877aa6e4906870d930e50cf144b" }
]
[env.staging.vars]
SUBGRAPH_API = "https://api2.neokingdom.org/subgraphs/name/CrowdpunkDAO"
EMAIL_FROM = "admin@crowdpunk.love"
EMAIL_TO = "nicola@neokingdom.org"
EMAIL_CC = "alberto@granzotto.net,stefano.ceschib@gmail.com"
ODOO_API = "http://85.209.49.64/jsonrpc"
DAO_URL = "https://dao.crowdpunk.love"

[env.production]
name = "crowdpunkdao-mailer"
workers_dev = true
kv_namespaces = [ 
         { binding = "CROWDPUNK_NAMESPACE", id = "98a84ae633fd48b3bbf066a45a5cb488" }
]
[env.production.vars]
SUBGRAPH_API = "https://api2.neokingdom.org/subgraphs/name/CrowdpunkDAO"
EMAIL_FROM = "admin@crowdpunk.love"
EMAIL_TO = "benjamin@neokingdom.org"
EMAIL_CC = "alberto@granzotto.net,stefano.ceschib@gmail.com,nicola@neokingdom.org"
ODOO_API = "http://85.209.49.64/jsonrpc"
DAO_URL = "https://dao.crowdpunk.love"

[miniflare]
env_path = ".env.test"             # --env
kv_persist = false                  # --kv-persist
cache_persist = "./cache"          # --cache-persist
host = "127.0.0.1"                 # --host
port = 1337                        # --port
watch = true                       # --watch
live_reload = true                 # --live-reload